'use client';
import { useEffect, useState } from 'react';
import { useKnowledge } from '@/stores/knowledge';
import { portfolioTotals, recordPerformance, performanceSummary, type Holding, type PerformancePoint, type Quote } from '@/knowledge/portfolio';
import { Sparkline } from './Sparkline';
export function Portfolio() {
  const [holdings, setHoldings] = useState<Holding[]>([]), [ready, setReady] = useState(false), [quotes, setQuotes] = useState<Record<string, Quote>>({});
  const [symbol, setSymbol] = useState(''), [shares, setShares] = useState(''), [cost, setCost] = useState(''), [sector, setSector] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [history, setHistory] = useState<PerformancePoint[]>([]);
  useEffect(() => { try { const value = JSON.parse(localStorage.getItem('nexus:portfolio') || '[]'); if (Array.isArray(value)) setHoldings(value.filter(h => typeof h.id === 'string' && /^[A-Z][A-Z0-9.-]{0,14}$/.test(h.symbol) && Number.isFinite(h.shares) && h.shares > 0 && Number.isFinite(h.cost) && h.cost >= 0 && typeof h.sector === 'string').slice(0, 20)); } catch { setError('Saved holdings could not be read.'); } try { const saved = JSON.parse(localStorage.getItem('nexus:portfolio-history') || '[]'); if (Array.isArray(saved)) setHistory(saved); } catch { /* ignore */ } setReady(true); }, []);
  useEffect(() => { if (!ready) return; try { localStorage.setItem('nexus:portfolio', JSON.stringify(holdings)); } catch { setError('Browser storage is unavailable. Changes are not saved.'); } }, [holdings, ready]);
  const { priced, value, basis, sectors } = portfolioTotals(holdings, quotes);
  useEffect(() => { if (ready) useKnowledge.getState().publish('stocks', { holdings, quotes, pricedCount: priced.length, value, costBasisForPricedHoldings: basis, sectors, note: 'User-entered holdings. Quotes may be delayed; missing quotes are not valued.' }); }, [holdings, quotes, ready]); // eslint-disable-line react-hooks/exhaustive-deps
  const refresh = async () => { setBusy(true); setError(''); const next: Record<string, Quote> = {}; let failure = '';
    for (const ticker of [...new Set(holdings.map(h => h.symbol))]) { try { const r = await fetch(`/api/accounts?module=stocks&symbol=${encodeURIComponent(ticker)}`); const d = await r.json(); if (!r.ok) { failure = d.error; break; } if (Number.isFinite(d.price)) next[ticker] = { price: d.price, timestamp: d.timestamp }; } catch { failure = 'Could not update portfolio prices.'; break; } }
    setQuotes(next); setError(failure); setBusy(false);
    const totals = portfolioTotals(holdings, next);
    if (totals.priced.length) { const updated = recordPerformance(history, totals.value, totals.basis); setHistory(updated); try { localStorage.setItem('nexus:portfolio-history', JSON.stringify(updated)); } catch { /* storage unavailable */ } }
  };
  return <section className="knowledge"><h3>Your portfolio</h3><p className="muted">Enter holdings in the quote’s trading currency. No brokerage account is linked. Do not combine different currencies in these totals.</p><form onSubmit={e => { e.preventDefault(); const ticker = symbol.trim().toUpperCase(), quantity = Number(shares), price = Number(cost); if (!/^[A-Z][A-Z0-9.-]{0,14}$/.test(ticker) || !Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(price) || price < 0 || holdings.length >= 20) { setError('Use a valid symbol, positive quantity and nonnegative cost. Maximum 20 holdings.'); return; } setHoldings(h => [...h, { id: crypto.randomUUID(), symbol: ticker, shares: quantity, cost: price, sector: sector.trim() }]); setSymbol(''); setShares(''); setCost(''); setError(''); }}><input aria-label="Holding symbol" placeholder="Symbol" value={symbol} maxLength={15} required onChange={e => setSymbol(e.target.value)} /><input aria-label="Share quantity" placeholder="Shares" type="number" min="0.000001" step="any" required value={shares} onChange={e => setShares(e.target.value)} /><input aria-label="Average cost per share" placeholder="Average cost per share" type="number" min="0" step="any" required value={cost} onChange={e => setCost(e.target.value)} /><input aria-label="Holding sector" placeholder="Sector (optional)" maxLength={50} value={sector} onChange={e => setSector(e.target.value)} /><button className="text-button" disabled={!ready}>Add holding +</button></form>
    {holdings.length > 0 && <button className="text-button" onClick={() => void refresh()} disabled={busy}>{busy ? 'Updating prices…' : 'Update portfolio prices'}</button>}{error && <p role="alert">{error}</p>}
    {priced.length > 0 && <><div className="diagnostics"><div><span>{priced.length === holdings.length ? 'Market value' : 'Priced holdings subtotal'}</span><strong>{value.toFixed(2)}</strong></div><div><span>Unrealized P/L · priced holdings</span><strong>{(value - basis).toFixed(2)}</strong></div></div><div className="allocation" aria-label="Sector exposure">{Object.entries(sectors).map(([name, amount], i) => <div key={name}><span>{name}</span><meter min={0} max={Math.max(value, 1)} value={amount} /><small>{value > 0 ? (amount / value * 100).toFixed(1) : '0'}%</small></div>)}</div><p className="muted">{priced.length} of {holdings.length} holdings priced. Finnhub timestamps are shown below.</p></>}
    {(() => { const s = performanceSummary(history); return s ? <div className="trend"><span>Performance · {s.days} day{s.days === 1 ? '' : 's'} observed</span><strong>{(s.change >= 0 ? '+' : '') + s.change.toFixed(2)}{s.percent !== null ? ` · ${(s.percent >= 0 ? '+' : '') + s.percent.toFixed(1)}%` : ''}</strong><Sparkline values={s.values} label="Portfolio value over time" /><p className="muted">Reconstructed from local daily snapshots recorded when you update prices. Not brokerage history.</p></div> : holdings.length > 0 ? <p className="muted">Update prices on separate days to build a performance curve.</p> : null; })()}
    <div className="knowledge-list">{holdings.map(h => <article key={h.id}><h3>{h.symbol} · {h.shares} shares</h3><p>Average cost {h.cost.toFixed(2)} · {quotes[h.symbol] ? `Quote ${quotes[h.symbol].price.toFixed(2)} at ${new Date(quotes[h.symbol].timestamp * 1000).toLocaleString()}` : 'Quote unavailable'}</p><button className="text-button" onClick={() => setHoldings(v => v.filter(item => item.id !== h.id))}>Remove holding</button></article>)}</div>
  </section>;
}
