import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle', timeout: 120000 });
await page.getByRole('heading', { name: 'Make space.' }).waitFor();
await page.getByRole('button', { name: 'Open Projects', exact: true }).waitFor({ timeout: 30000 });
await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Rotate right', exact: true }).click();
await page.getByRole('button', { name: 'Open Sports', exact: true }).waitFor();
await page.getByRole('button', { name: 'Open Sports', exact: true }).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.getByRole('dialog').innerText(), /Sports/);
await page.keyboard.press('Escape');
await page.keyboard.press('Control+k');
await page.getByRole('textbox', { name: 'Find a module' }).fill('system');
await page.getByRole('textbox', { name: 'Find a module' }).press('Enter');
await page.getByRole('dialog', { name: 'UNDER THE SURFACE / SYSTEM' }).waitFor();
assert.match(await page.getByRole('dialog', { name: 'UNDER THE SURFACE / SYSTEM' }).innerText(), /Render rate/);
await page.screenshot({ path: 'test-results/system.png' });
await page.keyboard.press('Escape');
await page.keyboard.press('h');
assert.equal(await page.getByRole('heading', { name: 'Make space.' }).count(), 0);
await page.keyboard.press('Control+k');
await page.getByRole('textbox', { name: 'Find a module' }).waitFor();
await page.keyboard.press('Escape');
await page.keyboard.press('h');
await page.getByRole('button', { name: 'CONTROLS', exact: true }).click();
assert.match(await page.getByRole('dialog').innerText(), /Pinch & release/);
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Enable hand tracking', exact: false }).click();
await page.getByRole('alert').waitFor({ timeout: 20000 });
assert.match(await page.getByRole('alert').innerText(), /camera/i);
await page.getByRole('button', { name: 'Dismiss camera error' }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('button', { name: 'Select Projects', exact: true }).last().click();
await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
const fallback = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await fallback.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { if (type === 'webgl2') return null; return original.call(this, type, ...args); }; });
await fallback.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle' });
await fallback.getByText('ACCESSIBLE MODE').waitFor();
await fallback.getByRole('button', { name: 'Open Projects', exact: true }).click();
await fallback.getByRole('dialog').waitFor();
assert.deepEqual(errors, []);
console.log('Passed: render, rotation, module panels, launcher, hidden-HUD launcher, guide, camera failure recovery, mobile width, WebGL fallback.');
await browser.close();
